### PR TITLE
docs: add a header and badges for better navigation to README

### PR DESCRIPTION
**Pull request by mfts**

### CODE REVIEW

**Comment by mxcl** [comment]
What are you goals with these changes? Because better navigation is not achieved. Linking to our discord *is* achieved, so that would be “adding community links”.

I'm fine with the badges and probs fine with the one-liner, though I feel it makes the subsequent pitch feel out of place so we may need to rework the whole thing.

I don’t want the H1 line though. The banner is the H1. Maybe the banner should be changed to the Gypsy one that just says `tea`.

**Comment by mfts** [comment]
Yes the org readme is so short I just wanted to add it for consistency. Can remove the H1 and nav links. 
I'd love to add the socials there and there should be a list of repos to get started. 
I forgot to add the `demos` repo.

**Comment by mxcl** [comment]
https://github.com/mfts/tea.github/blob/docs/improvements/profile/README.md

**Comment by mxcl** [comment]
Thank you for persevering through my unspecific criticisms.

**Comment by mxcl** [comment]
Can we customize the color for tea/cli to a vibrant pink or something @tsmitty11 to advise on color code.

**Comment by tsmitty11** [comment]
@mxcl Is this in reference to the badge that was added via this ticket? Or in reference to the tea/cli itself?

**Comment by mxcl** [comment]
@tsmitty11 [click here](https://github.com/mfts/tea.github/blob/docs/improvements/profile/README.md), third badge under the banner.

**Comment by tsmitty11** [comment]
@mxcl @mfts let's try tea's Magenta color (#ff00ff)

**Comment by mxcl** [comment]
done!

image

@tsmitty11 possibly you want to modify the other two colors a bit? If so LMK. If not cool.

**Comment by tsmitty11** [comment]
@mxcl the magenta looks great! For the other two, let's do:

#2675f5 = Twitter
#29f746 = Discord 

Same 'colors' generally speaking, but are yea tertiary colors from style guide.

**Pull request merged**
