### PR TITLE
CONTRIBUTING.md

### LINKED ISSUE #2: Update README To Enforce Smaller PRs
Some PRs submitted by the public are huge. We need to update the README so that we can enforce smaller PRs for changes making them easier to review and approve.

### PR DESCRIPTION
**Pull request by mxcl**
Closes #2

### CODE REVIEW

**Comment by mxcl** [comment]
Rendered: https://github.com/teaxyz/.github/blob/contributing/CONTRIBUTING.md

**Comment by mxcl** [comment]
refactors footnote is screwed for some reason

**Review by jhheider — APPROVED** [review]
Perf.

**Comment by jhheider** [comment]
> refactors footnote is screwed for some reason

Can't push, missing colon on line 24.

**Comment by mxcl** [comment]
> Can't push, missing colon on line 24.

Fixed thanks

**Pull request merged**
